# Generated by Django 5.2 on 2025-04-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="instructor_portal.course",
            ),
        ),
    ]
