# Generated by Django 5.2 on 2025-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor_portal", "0002_course_thumbnail_resource_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="coursematerial",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="grade",
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                default="document",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="total_points",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(upload_to="course_resources/"),
        ),
    ]
