# Generated by Django 5.0.2 on 2025-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField()),
                ('current_position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='alumni/')),
                ('story', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni Success Stories',
                'ordering': ['order', '-graduation_year'],
            },
        ),
    ]
