# Generated by Django 4.2.18 on 2025-04-09 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
