# Generated by Django 5.2 on 2025-05-03 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Untitled Assignment', max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
