# Generated by Django 5.0.2 on 2025-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='democlass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
