# Generated by Django 5.0.2 on 2025-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_payment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_installment',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment Payment')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
