# Generated by Django 5.0.2 on 2025-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_invoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_warning_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_installment_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
