# Generated by Django 4.2.18 on 2025-03-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stud_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="date_enrolled",
        ),
        migrations.AddField(
            model_name="completedlesson",
            name="enrolled_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_lessons",
                to="stud_portal.enrolledcourse",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="stud_portal.course",
            ),
            preserve_default=False,
        ),
    ]
