# Generated by Django 4.2.18 on 2025-03-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("stud_portal", "0002_remove_enrolledcourse_course_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolledcourse",
            name="enrollment_date",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrolledcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
