# Generated by Django 4.2.18 on 2025-04-11 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stud_portal", "0005_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
