# Generated by Django 4.2.18 on 2025-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stud_portal", "0007_profile_instructorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_completed_profile",
            field=models.BooleanField(default=False),
        ),
    ]
