# Generated by Django 4.2.18 on 2025-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
