# Generated by Django 4.2.18 on 2025-02-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_alter_banner_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon_class", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="HighlightFeature",
        ),
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banners/"),
        ),
    ]
