# Generated by Django 4.2.18 on 2025-03-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "homepage",
            "0003_feature_delete_highlightfeature_alter_banner_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
    ]
